version: '3.1'
services:
#  app:
#    network_mode: host
#    build: .
#    container_name: crm
#    restart: always
#    ports:
#      - "8080:8084"
#    depends_on:
#      - postgres

  postgres:
#    network_mode: host
    image: "postgres:14-alpine"
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: lab3
    ports:
      - "5433:5432"
    volumes:
      - ./epitome_data:/data/db
